image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: 12

primary:
  initdb:
    scriptsSecret: 'postgres-initdb-scripts'
  persistence:
    enabled: False
  extendedConfiguration: |
    max_connections = 400
    shared_buffers = 1024MB
  resources:
    limits:
      memory: "1Gi"
      cpu: "1.0"
    requests:
      memory: "1Gi"
      cpu: "1.0"
  nodeSelector:
    kubernetes.io/hostname: ucsd-nrp.cern.ch 
  tolerations:
    - key: "nautilus.io/reservation"
      value: "sense"
      operator: "Equal"
      effect: "NoSchedule"

